# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fd129712b538de26812b9c7418b9cd40c1503f96161ac47958bfacb0ebfa10eb7546ebaa9e146bd4e765286f7baebdb49854bdf72fbf84d85fc0d7093de33dd

test:
  secret_key_base: f0ed783b5973dd2982f352dc8adb0ee0114f3ddbe4c4869556a269ab8b193f4ed35e0226e6ba69c13fc31bd580ed66f1ab07a6a388a37efa5c7d263ac9b8643a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
